#服务端口
server:
  port: 9101

spring:
  #服务名
  application:
    name: lucky-shop-mobile-auth

  main:
    allow-bean-definition-overriding: true

  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucky-shop?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  #Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8

  #Cloud相关配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# Oauth2相关配置
auth:
  oauth2:
    #密码模式
    grant_type: password
    client_id: mobile
    client_secret: mobile
    #获取token地址
    access-token-url: http://localhost:9101/oauth/token

management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapperxml/*Mapper.xml
  # 搜索指定包别名
  typeAliasesPackage: com.lucky.shop.mobile.auth.domain
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.lucky.shop.admin.auth: debug
    org.springframework: debug
